help for the installer

diff --git a/bin/0xMF-dotfiles b/bin/0xMF-dotfiles
--- a/bin/0xMF-dotfiles
+++ b/bin/0xMF-dotfiles
@@ -478,6 +478,7 @@ install() {
 if [ -z "$1" ]; then
   check_installer_shell
   help
+  >&2 echo "ERROR!!! Missing command: install"
 else
   if [ "$1" = "install" ]; then
     shift
